project_id = "ltjxuknxsewsbtggjbee"

[functions.fashn-api]
verify_jwt = true

[functions.replicate-api]
verify_jwt = true

[functions.gemini-api]
verify_jwt = true

[functions.kie-ai]
verify_jwt = true

[functions.fashn-webhook]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false

[functions.gemini-webhook]
verify_jwt = false

[functions.kie-webhook]
verify_jwt = false