project_id = "ltjxuknxsewsbtggjbee"

[functions.fashn-api]
verify_jwt = true

[functions.replicate-api]
verify_jwt = true

[functions.fashn-webhook]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false