// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltjxuknxsewsbtggjbee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0anh1a254c2V3c2J0Z2dqYmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjg2NjEsImV4cCI6MjA2OTkwNDY2MX0.-1_04nWqtMNtTnBvpKqd9oDje9Unt-1J1PC1GcXxzuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});